server:
  port: 9192

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/lakeSideHotelDb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 20KB
